version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - internal

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskflow
    depends_on:
      - mongo
      - notification-service
      - log-service
    networks:
      - internal

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "4000:4000"
    networks:
      - internal

  log-service:
    build:
      context: ./log-service
    container_name: log-service
    ports:
      - "5000:5000"
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - internal

volumes:
  mongo-data:

networks:
  internal:
    driver: bridge
